[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = true

[rpc_endpoints]                                                                                                                    
  arbitrum_sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"                                                                                        
                                                                                                                                  
[etherscan]                                                                                    
  arbitrum_sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=42161" }

[lint]
# ... rest of lint config ...
exclude_lints = ["unaliased-plain-import","mixed-case-variable","mixed-case-function"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
